services:
  mycontainer:
    build: .
    image: "docker.io/org_name/image_name"      # Always provide FQDN image names!
    platform: linux/amd64
    volumes:
      - my-volume:/root/.my-volume              # Persistent per-machine storage.
      - /run/rofl-appd.sock:/run/rofl-appd.sock # appd REST API.
    environment:
      - CONTRACT_ADDRESS=0x8d9e9704D1006b8d0BA0F58169cA8bA2de6DCD88           # See `oasis rofl secret` command.
      - TICKER=BTCUSDT

volumes:
  my-volume:
