services:
  mycontainer:
    build: .
    image: "docker.io/longdevdatabase/test_rofl:latest"      # Always provide FQDN image names!
    platform: linux/amd64
    volumes:
      - my-volume:/root/.my-volume              # Persistent per-machine storage.
      - /run/rofl-appd.sock:/run/rofl-appd.sock # appd REST API.
    environment:
      - CONTRACT_ADDRESS=0xf7e03Eed20bd0cfBf2083679066e2E92Ceb4e693
      - TICKER=ROSEUSDT

volumes:
  my-volume:
